POST http://127.0.0.1:8000/api/qa/create
# PUT http://127.0.0.1:8000/api/qa/edit/14

{
    "title": "AjouUt QA par l'API 7450",
    "promoted": 1,
    "status": "draft",
    "answers": [{
        "channel": "faq",
        "body":"<p>grg hgrugurgij krkgg</p>"       
    }]
}